### ISSUE TITLE
Error with pasty installed via conda

### ISSUE THREAD

**Issue by erinyoung** [rpetit3/pasty#2]
I think this is a blast issue as opposed to a pasty issue, but I thought I would let you know that this is the error I got with a conda installation.

```
$ pasty --assembly GCF_001457615.1_NCTC10332_genomic.fna
Running pasty with following parameters:
    --assembly /Volumes/IDGenomics_NAS/ARLN/ncbi_dataset/data/GCF_001457615.1_NCTC10332_genomic.fna
    --db /home/eriny/miniconda3/share/pasty-1.0.2/OSAdb.fasta
    --prefix GCF_001457615.1_NCTC10332_genomic
    --outdir ./
    --min_pident 95
    --min_coverage 95

Running BLASTN...
External command isn't available!

Command:
bash -c 'cat /Volumes/IDGenomics_NAS/ARLN/ncbi_dataset/data/GCF_001457615.1_NCTC10332_genomic.fna | blastn -query - -subject /home/eriny/miniconda3/share/pasty-1.0.2/OSAdb.fasta -outfmt
'"'"'6 qseqid sseqid pident qlen slen length nident positive mismatch gapopen gaps qstart qend sstart send evalue bitscore qseq sseq'"'"''

Search path:
['/home/eriny/miniconda3/bin',
 '/home/eriny/miniconda3/condabin',
 '/home/eriny/.local/bin',
 '/home/eriny/bin',
 '/home/linuxbrew/.linuxbrew/bin',
 '/home/linuxbrew/.linuxbrew/sbin',
 '/usr/local/bin',
 '/usr/bin',
 '/usr/local/sbin',
 '/usr/sbin',
 '/home/Bioinformatics/sratoolkit.2.11.3-centos_linux64/bin',
 '/home/Bioinformatics/edirect']
```

**Comment by rpetit3** [comment]
Hi @erinyoung,

One thing that sticks out is the search path for $PATH. Unless its installed in the `base` environment, there doesn't seem to be anything related to a pasty environment to it.

Even then, agree with you, `blastn` should have still been installed with Conda.

I'll test on my end. 

Cheers,
Robert

**Comment by erinyoung** [comment]
It was a temporary virtual environment, so everything was getting installed in base.

**Comment by rpetit3** [comment]
Ah, any logs to verify blast was installed? I'm unable to replicate locally, when creating a new environment.

**Comment by rpetit3** [comment]
Hi @erinyoung 

Been a while, I added a `--check` option to pasty to check for dependencies.

Going to close for now, feel free to reopen if you think this is an issue with pasty specifically.

Robert
